[DRAFT] Privacy policy copy
MyCryptoHQ/landing pull request #63
Opened 2021-02-12 00:00 UTC by 409H

- Added copy for Segment DW usage 

@vilsbole before merging we need signoff from Luker

2021-02-15 19:07 UTC, LuckyLuker commented on src/assets/content/privacy-policy.md
> +Our main product offering ([MyCrypto App](https://app.mycrypto.com)) makes use of [Segment](https://segment.com/) for a data warehouse for anonymised analytics data. We collect the data grouped by th
for a data warehouse for anonymised analytics data. -> as a data warehouse for anonymized analytics data.

2021-02-15 19:14 UTC, LuckyLuker commented on src/assets/content/privacy-policy.md
> +You can learn about how Segment is privacy-first data storage warehouse platform that enables companies, like MyCrypto, to respect users' privacy [here](https://segment.com/legal/privacy/).
Segment is privacy-first data -> Segment is a privacy-first data

2021-02-16 09:52 UTC, vilsbole requested changes
lgtm;
Please ping me once Luker's comments are addressed.

2021-02-23 12:31 UTC, vilsbole approved these changes

2021-02-23 12:31 UTC, merged