remove Emmanuel
MyCryptoHQ/landing pull request #78
Opened 2021-06-16 10:23 UTC by 409H

2021-06-16 11:37 UTC, GuillaumeRx requested changes

2021-06-16 11:37 UTC, GuillaumeRx commented on src/assets/team-profiles/team.ts
> -import emmanuel from './emmanuel.jpg';
Please remove this asset

2021-06-16 17:59 UTC, 409H commented on src/assets/team-profiles/team.ts
> -import emmanuel from './emmanuel.jpg';
Ah, my bad (lazy). Pushed in 4ed3942

2021-06-28 18:20 UTC, GuillaumeRx approved these changes
lgtm

2021-06-28 18:20 UTC, merged